// src/utils/roles.js

import { PERMISSIONS } from './permissions.js'

export const ROLES = {
  SUPERADMIN: {
    name: 'superAdmin',
    permissions: [
      PERMISSIONS.CREATE_USER,
      PERMISSIONS.UPDATE_USER,
      PERMISSIONS.DELETE_USER,
      PERMISSIONS.VIEW_USERS,
      PERMISSIONS.ASSIGN_ROLES_TO_USERS,
      PERMISSIONS.CREATE_ROLE,
      PERMISSIONS.UPDATE_ROLE,
      PERMISSIONS.DELETE_ROLE,
      PERMISSIONS.VIEW_ROLES,
      PERMISSIONS.ASSIGN_PERMISSIONS_TO_ROLES,
      PERMISSIONS.ADD_BOOK,
      PERMISSIONS.UPDATE_BOOK,
      PERMISSIONS.DELETE_BOOK,
      PERMISSIONS.VIEW_BOOKS,
      PERMISSIONS.SEARCH_BOOKS,
      PERMISSIONS.APPROVE_BORROW_REQUESTS,
      PERMISSIONS.VIEW_BORROWED_BOOKS,
      PERMISSIONS.SEND_NOTIFICATIONS,
      PERMISSIONS.VIEW_NOTIFICATIONS,
      PERMISSIONS.VIEW_SYSTEM_LOGS,
      PERMISSIONS.SYSTEM_CONFIGURATION,
      PERMISSIONS.MANAGE_USERS_AND_ROLES,
      PERMISSIONS.MANAGE_BOOKS_AND_BORROWING
    ]
  },
  ADMIN: {
    name: 'admin',
    permissions: [
      PERMISSIONS.CREATE_USER,
      PERMISSIONS.UPDATE_USER,
      PERMISSIONS.DELETE_USER,
      PERMISSIONS.VIEW_USERS,
      PERMISSIONS.ADD_BOOK,
      PERMISSIONS.UPDATE_BOOK,
      PERMISSIONS.DELETE_BOOK,
      PERMISSIONS.VIEW_BOOKS,
      PERMISSIONS.APPROVE_BORROW_REQUESTS,
      PERMISSIONS.VIEW_BORROWED_BOOKS,
      PERMISSIONS.SEND_NOTIFICATIONS,
      PERMISSIONS.VIEW_NOTIFICATIONS
    ]
  },
  LIBRARIAN: {
    name: 'librarian',
    permissions: [
      PERMISSIONS.ADD_BOOK,
      PERMISSIONS.UPDATE_BOOK,
      PERMISSIONS.DELETE_BOOK,
      PERMISSIONS.VIEW_BOOKS,
      PERMISSIONS.APPROVE_BORROW_REQUESTS,
      PERMISSIONS.VIEW_BORROWED_BOOKS
    ]
  },
  CLIENT: {
    name: 'client',
    permissions: [
      PERMISSIONS.VIEW_BOOKS,
      PERMISSIONS.BORROW_BOOKS,
      PERMISSIONS.RETURN_BOOKS,
      PERMISSIONS.VIEW_BORROWED_BOOKS
    ]
  }
}
